ansible_become_pass: ENC[AES256_GCM,data:RaRbhBkpvvA=,iv:2XTJTzFGuVYz9w8BRDCeE+v3UojK8AMPw2gNP3eoKSg=,tag:IXOYb9Bv+dXdq/JL99J5Sg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sjqyhkry5v2y5javn6l3f2pe2ezf3nvnp09unyevw9gl9pl5ddlsqdwkm8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrV1RIcHhWK2sxaHJjWGVW
            U2llSERhb3QzdEt5R0NVclNDWlorN2hsSmhNCkZTUGVNRWg0MThIaGlXcGFCTzBW
            TU1hQWZ2TlVYMjFibXh5dVRiMWxFK1UKLS0tIDFwYXlCWlk2MDUxck0yekIvclZj
            N1kxVnNZNDEyaDE2MjRUSUR5VXUxRnMKGAL70rZQzBpuzOk/Pp9OcdB3g7jFKSus
            L4Z0g8BzSlIteRbR1JHgpy51YVcUJre8+Yr7SJu7DB/g5sXobU1YtQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-27T23:04:39Z"
    mac: ENC[AES256_GCM,data:4BuFCr2Wtj3vskDMSCA5nSQ4vCReZjj0UTaGL+dyiydP1/JulFlVLGfwUh0AL/yQK8aC+V0iq8Bsy6Lac5awmUTakLsgSeFS0ay9KrjE+erVGgEQcljo4xhl/W497dTzIW7yV09zvITjg2yo0BnIsMoluHL3Lv2hhzILddivVMo=,iv:OI7YnEHi7Yksd0mxsVraHuyDi32GRRfoi7hdFPTv14U=,tag:+NE9YiZ0wPfeAv2kqMKVBw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
