apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
stringData:
    admin-password: ENC[AES256_GCM,data:dnU+N0o=,iv:Yp3EHzykDjNP2+XqVdvkaSaErMRGgEsUsmF7GQ+I5dE=,tag:LCknAFBckKtCrVQeTYR8IQ==,type:str]
    admin-user: ENC[AES256_GCM,data:eLZts+4=,iv:sLGZFmMu5GCh2xgDEjU1KYK8CIyoRqT9bz1g3mGD2Tw=,tag:Yy9RwRdNxJqVL9dfE3ENKA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sjqyhkry5v2y5javn6l3f2pe2ezf3nvnp09unyevw9gl9pl5ddlsqdwkm8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUZ1o2SGJvem0wY1g3TmZD
            cVNsM04xVjFDRXZvVEpwcERrdVNLWUlJZEFjCnErTGFEcHNjWU14SHJ3QjJNV0dt
            UEh2WExCSDUxbjNsZDdkYit2S1ZEbTAKLS0tIHUyRC9zNGlSK2FlQVl6dlVYZFdO
            YUpoczVQcTVqbWhndHp6cE5xYnhyLzgKTBwG4jaGWGLeY/FXSyiIYJUySpkUECJK
            IZDBi1os+sWw+o23lfrQKibw4esnddTnLkxRL/RXW/wg20Kdauwt3Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-27T23:05:18Z"
    mac: ENC[AES256_GCM,data:/sUhfP8ZoQ0eEuEHJtVhg5hXzZyTbr8qgm8X0Wr9DIX6ZDlEU42BNfn0b6YrQ0K2UmCUwF+yJGqapi1xMRu5xoFEEU/+3FnCQaLFHHz0Yrzuc7Hvz12wxGO5QzWQukarQy/68qv3v94jWK7QMZ7ULO3RnlWLy0DF6q79bWitTI4=,iv:nXlW5GDYTucR3godbOVS6acgGlq83ymlaaKDYkLyY/A=,tag:fJQS3UC+1otzVFp46ZWbxw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
