apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:cmfpu8FkOZMw+6rXDSVXNuBTiyTHQ3tJ,iv:xBCNPvMNC9X0ff2J+7vVkY6W+aJUWP5V2g7UHbd5Ii4=,tag:Sd7JjMEtxS4d1Kw/fzlYaw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sjqyhkry5v2y5javn6l3f2pe2ezf3nvnp09unyevw9gl9pl5ddlsqdwkm8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPK1lJcHduNWVTbGZYUU1v
            cDZvOFlUWGswVHJINndMKzgrbUhRSzUwRVFZCkEwRWdzUC9qU01lRVhWMmZVallO
            cmRnL2xTTU5hY3h2ZFJxUHhMQUVjN1kKLS0tIDlEc0xOQkhndG1VRzN6NGFQa09X
            dFFVSTYra3dLejh0am5SNzJsN0dpTkEK+6LUWrE0VCbBLuhw8rVT2380/B30LHdX
            Gnsw3zDbHSxT10GQhwLVU0+ittmp7/1D8HqiGyLf1NbNgKn5i4GpXw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-27T08:05:50Z"
    mac: ENC[AES256_GCM,data:HwmbpYoKttQsM9Fu6mVNmLPNmpOtwf6bCyXZVs2S2Ui/H2/GGn+jnWB8v40I2NXTyb6IW/tte6YxyJbIVxGlh0QpGWKLo75aHcKqd4ABRMcfdwWelxMqRvCkFAB7njJR1gorKbVazm8GNuiQo86RYjUR6q94ts43LVRmHU7oKs4=,iv:Z1s52wD/2YYrsvSLm8K0l7rVyrIw3ElQhy2iC5Kd5Ho=,tag:5XJFZd5WlRrwaBG5tkfyZg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
