apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:NwVz7RUliHDYVI+t3XNEB/FGh4sgz+/d,iv:vLlgbn0aEoNf3eaynYmJTsbfNTw7d0p1Mh+wAwOZFG0=,tag:Or9AGRmZE2W7VEVBE+MD5Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sjqyhkry5v2y5javn6l3f2pe2ezf3nvnp09unyevw9gl9pl5ddlsqdwkm8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0OVZCaFVEUEhEWkVtQkxH
            c1B2SWZ2MW5RWTNaS09YWFlkejNsYjc3L2xBClVhNGtJczdaemRySW9aREFIZ2Fw
            SkE0cnlMN3ZXT29yaXpPelpseDRyN3MKLS0tIDIzMSswUWhsbXk1eDJkaGlHM05v
            TSthODJLZHBMdGJ0RUlROUhOaXNGTnMKUZh94NWv4zhlZ1tcgOQ6DhMIa8v62lPo
            LsY3nkiMzZdNQl9YPRdGReirIOgVEQt/FFkRQLeZTAFwDFSFJ4FQZg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-27T23:05:15Z"
    mac: ENC[AES256_GCM,data:DrMHdRSlIDVUvdPTi9LuKlgrEPnlIIIuidmAfsuoUDDNEMaafUBHo1d1prr1df173pmw7V3/GJZOTXK0QeS2izRW85DZOAh9q8EZmWyP4jjsbSXeARVSpYYWo7ADL8LnR5BGvmI5lo/ZQ8GCVGP+hgLJhsI6zpgLTeWFE1+l/zc=,iv:lLGUHtorEqwb5PjtPx0Tz2dJeRmTMXj3pclo+YlR+Do=,tag:7ZhMj59LNjx8GKsiHmWBvg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
