apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    SECRET_PLACEHOLDER: ENC[AES256_GCM,data:KuaaNJ/vMqfRZoVS,iv:l+AcQgxcUwT7p7sw9xKzBK44zXJxscMxLEHc6PdaKVo=,tag:x1ycnlXokMTf/N6ivYWaAQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sjqyhkry5v2y5javn6l3f2pe2ezf3nvnp09unyevw9gl9pl5ddlsqdwkm8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzUkd6NVZwVjZSc2xNTlho
            Y3B0eUVaZDA5RnBlQmlUN01xMzlSd3A1RlVRCmQ2b1FrampUMHd1clRuS2FwQUV6
            VlQvSmNKejV4Z2dXSE1lOTJzK2kvVGsKLS0tIFJLU2JwQ2I2d0pEQnY1VGxoekJM
            b2NqdkRyam9xS1JvR1phS0RiRWU3WmMKrHjEU14jHxb7Kk07XsJpxsL1tYHj7Kos
            LckJYLkHzwggZ0XX1d5VEe/MZBJtvgetp3i0YBN7tVb9CQoez3NNIw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-27T23:05:14Z"
    mac: ENC[AES256_GCM,data:QtO/XQzv5K2p46crcYBEBCRVOmTUngG72MDoTfvL79gN6eK0093z0srrGrdRLaA6P5j6SGuBBv2JU6vH99Phr9Acdrc/uJAvAjPvt1vBHVCg1hQmuoum7y8tJ7MLu9AnhCgumnHqBQ5zRpwxX+RLpC9ia8BluTqretpDNwfsoBg=,iv:TAIG0P6Ls0Gwhq2fsquHQ5HWVrEekFxx4StVjgT3BMU=,tag:+/lJmHu72mivxkvi4GEyLQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
