apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    SECRET_PLACEHOLDER: ENC[AES256_GCM,data:V3JELnmyTgWjtyWV,iv:ensgmquHH9AZO9cxKDjKFXxonA5zYFosq4MF9pgPPNQ=,tag:+qapIOpLRaFPCwTtDDnppg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sjqyhkry5v2y5javn6l3f2pe2ezf3nvnp09unyevw9gl9pl5ddlsqdwkm8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhcjB3MnVMdkN4am56ZWYw
            VFBLaXNTaFI1WFoxZVhySm5nNm8xZ2xwR2xvCkJ3b2MyUUZuYWtlY3FhYmw2RlZW
            dzQyNVNxVDl3MGY0V2t6ME80S1JYTkUKLS0tIExieW1aUnlNU0NnRjhWR0REYmZn
            MUVlcWU3VHlXYnBCLzl4em1ZM1JsS0EKuUMTgNVO7HMP5UV5zH70GGZwqMCEr/z0
            6qDJ0lCVGSVP9o+6WmzVzbZzRTpdWIJ45/tPHP7k+tPkb1VXidN/IA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-27T08:05:50Z"
    mac: ENC[AES256_GCM,data:Umotz8QqAR9ijM7Q9Me8oUTfQjKQKVwi+2i9Yf+t7GWJNHnBXl7B6g6I5ePhfkQ4QlMlvVjRIYtjLhvUfXmzsKmjquLgQPIuAx0sRmHIgybXk271PniQ2vPpG87on0WNlU6FbnNtLqRSzeJs1sRaOxLKD6xwMCjsEd+N8fkFER4=,iv:mun+yJslRix0N58oBNM+2Zhzu4dt7QgJ0/6J+HTzIFM=,tag:WzacTl6jPo9ehn5RKJdCNA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
